version: '3.8'

services:
  gateway:
    image: nginx:alpine
    ports:
      - "91:80"
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "./nginx/fastcgi.conf:/etc/nginx/fastcgi.conf"
      - "./nginx/mime.types:/etc/nginx/mime.types"
      - "./nginx/sites:/etc/nginx/conf.d/"
    depends_on:
      - mysql
    networks:
      - app-network
  
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_DATABASE=laravel
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
    networks:
      - app-network

  ms-manage:
    build:
      context: ../manage
      dockerfile: ./docker/php-fpm/Dockerfile
    restart: on-failure
    working_dir: /var/www
    volumes:
      - ../manage:/var/www
    depends_on:
      - mysql
    networks:
      - app-network

  ms-kitchen:
      build:
        context: ../kitchen
        dockerfile: ./docker/php-fpm/Dockerfile
      restart: on-failure
      working_dir: /var/www
      volumes:
        - ../kitchen:/var/www
      depends_on:
        - mysql
      networks:
        - app-network

  ms-invetory:
    build:
      context: ../warehouse
      dockerfile: ./docker/php-fpm/Dockerfile
    restart: on-failure
    working_dir: /var/www
    volumes:
      - ../warehouse:/var/www
    depends_on:
      - mysql
    networks:
      - app-network

volumes:
  db:
    driver: local

networks:
  app-network:
    driver: bridge

  